version: "3.8"

services:
    cypress-runner:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            DEBUG: ""
        volumes:
            - .:/e2e
            - screenshots:/e2e/cypress/screenshots/reserva_padel.cy.js
            - cypress-logs:/e2e/cypress/logs
        working_dir: /e2e

volumes:
    screenshots:
    cypress-logs:
